### PR TITLE
JS: Fix semantic merge conflict: Implement new signature members in StepInputSig

### PR DESCRIPTION
**Pull request by asgerf**
Fixes a semantic merge conflict between https://github.com/github/codeql/pull/18467 and https://github.com/github/codeql/pull/18298

### CODE REVIEW

**Review by erik-krogh — APPROVED** [review]

**Comment by redsun82** [comment]
@asgerf wdyt, can we merge this as is to unblock `main`, and do a follow-up PR maybe implementing @hvitved's suggestion and adding the missing doc comments?

**Comment by redsun82** [comment]
> @asgerf wdyt, can we merge this as is to unblock `main`, and do a follow-up PR maybe implementing @hvitved's suggestion and adding the missing doc comments?

ah, no the red check is due to the very compilation error this sets out to fix :+1:
